<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="37873" started-at="2020-03-18T08:29:21 IST" finished-at="2020-03-18T08:29:59 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="37873" started-at="2020-03-18T08:29:21 IST" finished-at="2020-03-18T08:29:59 IST">
      <class name="com.sauce.testcases.TestCases">
        <test-method status="PASS" signature="open_browser()[pri:0, instance:com.sauce.testcases.TestCases@22a67b4]" name="open_browser" is-config="true" duration-ms="9424" started-at="2020-03-18T08:29:21 IST" finished-at="2020-03-18T08:29:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open_browser -->
        <test-method status="PASS" signature="login()[pri:0, instance:com.sauce.testcases.TestCases@22a67b4]" name="login" duration-ms="26111" started-at="2020-03-18T08:29:31 IST" finished-at="2020-03-18T08:29:57 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="verifyCart()[pri:1, instance:com.sauce.testcases.TestCases@22a67b4]" name="verifyCart" duration-ms="20" started-at="2020-03-18T08:29:31 IST" finished-at="2020-03-18T08:29:31 IST">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.sauce.testcases.TestCases.verifyCart(TestCases.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCart -->
        <test-method status="PASS" signature="close_browser()[pri:0, instance:com.sauce.testcases.TestCases@22a67b4]" name="close_browser" is-config="true" duration-ms="2103" started-at="2020-03-18T08:29:57 IST" finished-at="2020-03-18T08:29:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close_browser -->
      </class> <!-- com.sauce.testcases.TestCases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
